name: student-performance-mlflow-ci

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  train-and-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: "3.10"

    - name: Install MLflow
      run: |
        pip install --upgrade pip
        pip install mlflow

    # ===============================
    # Run Training as MLflow Project
    # ===============================
    - name: Run Training with MLflow Project
      run: |
        mlflow run MLProject

    # ===============================
    # Debug
    # ===============================
    - name: Debug MLProject files
      run: |
        ls -la MLProject
        cat MLProject/run_id.txt

    # ===============================
    # Upload mlruns (OPSIONAL tapi aman)
    # ===============================
    - name: Upload MLflow artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mlruns
        path: MLProject/mlruns/

    # ===============================
    # Login Docker Hub
    # ===============================
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # ===============================
    # Build Docker Image
    # ===============================
    - name: Build Docker image with MLflow
      run: |
        cd MLProject
        RUN_ID=$(cat run_id.txt)

        mlflow models build-docker \
          -m runs:/${RUN_ID}/model \
          -n ${{ secrets.DOCKERHUB_USERNAME }}/student-performance-mlflow \
          --enable-mlserver

    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/student-performance-mlflow
